- name: Deploy Monitoring Stack
  run: |
    ssh ubuntu@${{ secrets.SERVER_IP }} "
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts &&
    helm repo update &&
    helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
    --namespace monitoring --create-namespace"
